site_name: lernOS Digitales Ökosystem Leitfaden
site_url: https://cogneon.github.io/
docs_dir: src
site_dir: ../docs/de

nav:
    - Willkommen: index.md
    - Grundlagen: 1-0-Basics.md
    - Lernpfad:
      - Überblick: 2-0-Lernpfad.md
      - Digitalisierung: 2-1-Digitization.md
      - Digitale Ökosysteme: 2-2-Digital-Ecosystems.md
      - Gelegenheiten: 2-3-Opportunities.md
      - Rollen: 2-4-Roles.md
      - Geschäftsmodell: 2-5-Business-Model.md
      - Typen: 2-6-Types.md
      - Phasen: 2-7-Phases.md
      - Mindset: 2-8-Mindset.md
      - Monetarisierung: 2-9-Monetization.md
      - DATEV: 2-10-DATEV.md
      - SAP: 2-11-SAP.md
      - Continental: 2-12-Continental.md
    - Anhang: 3-0-Anhang.md
    - Download:
      - PDF-Version: https://github.com/cogneon/lernos-digitales-oekosystem/blob/master/de/build/lernos-template-guide.pdf
      - Word-Version: https://github.com/cogneon/lernos-digitales-oekosystem/blob/master/de/build/lernos-template-guide.docx
      - HTML-Version: https://github.com/cogneon/lernos-digitales-oekosystem/blob/master/de/build/lernos-template-guide.html
      - E-Book (epub): https://github.com/cogneon/lernos-digitales-oekosystem/blob/master/de/build/lernos-template-guide.epub
    - Links:
      - lernos.org: https://lernos.org
      - CONNECT Community: https://community.cogneon.de
      - Peerfinder: https://web.peerfinder.app

theme:
    name: 'material'
    custom_dir: src/overrides
    palette:
        scheme: lernos
    language: de
    icon:
      logo: material/home
      repo: fontawesome/brands/github

extra_css:
  - stylesheets/extra.css

repo_name: 'cogneon/lernos-template'
repo_url: 'https://github.com/cogneon/lernos-digitales-oekosystem'

extra:
    social:
        - icon: fontawesome/brands/mastodon
          link: 'https://colearn.social/@lernos'
        - icon: fontawesome/brands/linkedin
          link: 'https://www.linkedin.com/showcase/lern-os'
        - icon: fontawesome/brands/github
          link: 'https://github.com/cogneon'
    disqus: lernos
    analytics:
       provider: custom

plugins:
  - search
